### ISSUE TITLE
Add Patagonia, Osprey, Peak Designs bags

### ISSUE THREAD

**Issue by mihaiv** [JenniferMack/BagsVsAirlines#12]
Patagonia MLC 1,655 g (3 lbs 10.4 oz)22.8" x 8.6" x 14.5"45L (2,746 cu in) - https://www.patagonia.ca/product/black-hole-mlc-briefcase-backpack-45-liters/49306.html

Osprey Farpoint 40 https://www.osprey.com/us/en/product/farpoint-40-FARPNT40.html

Peak Designs Travel Backpack https://www.peakdesign.com/products/travel-backpack

**Comment by JenniferMack** [comment]
add for next update
