### ISSUE TITLE
Add Pelican MPB Backpacks

### ISSUE THREAD

**Issue by ktaui** [JenniferMack/BagsVsAirlines#13]
Pelican MPB 35L: 14.9 x 7.8 x 24.4 inches, 2.43 pounds
37.8 x 19.8 x 61.9 cm, 1.10 kg
https://preview.tinyurl.com/y64rpfyb

Pelican MPB 25L: 15.7 x 6.7 x 21.2 inches, 1.98 pounds
39.8 x 17 x 53.8 cm, 0.89 kg
https://preview.tinyurl.com/y43uvzdm

Pelican MPB 20L: 13.7 x 5.1 x 21.6 inches, 1.43 pounds
34.7 x 12.9 x 54.8 cm, 0.64 kg
https://preview.tinyurl.com/y3qjlprw

**Comment by JenniferMack** [comment]
added for next update
