### ISSUE TITLE
Some european airlines 

### ISSUE THREAD

**Issue by Thapsus** [JenniferMack/BagsVsAirlines#3]
A few european airlines worth adding. Based on cheapest economy classes or equivalent.
Sizes in mm
Weight in Kg.

**Air France**
Carry-on size : 550 x 350 x 250
Carry-on weight : 12 (Carry-on + Personal item)

Personal item size : 400  x 300 x 150
Personal item weight : 12 (Carry-on + Personal item)

Source : `https://www.airfrance.fr/FR/fr/common/guidevoyageur/pratique/bagages-cabine-airfrance.htm`

**KLM**
Carry-on size : 550 x 350 x 250
Carry-on weight : 12 (Carry-on + Personal item)

Personal item size : 400  x 300 x 150
Personal item weight : 12 (Carry-on + Personal item)

Source : `https://www.klm.com/travel/fr_fr/prepare_for_travel/baggage/baggage_allowance/index.htm`

**Iberia**
Carry-on size : 560 x 450 x 250
Carry-on weight : N/A

Personal item size : 400  x 300 x 150
Personal item weight : N/A

Source : `https://www.iberia.com/fr/bagages/a-main/`

**Easyjet**
Carry-on size : 560 x 450 x 250
Carry-on weight : N/A

Personal item size : -
Personal item weight : -

Source : `https://www.easyjet.com/fr/aide/bagage/bagage-a-main-et-bagage-en-soute`

**SAS**
Carry-on size : 550 x 400 x 230
Carry-on weight : 8

Personal item size : 400 x 300 x 150
Personal item weight : 8

Source : `https://www.flysas.com/fr-fr/informations-sur-le-voyage/bagages/bagage-a-main/`

**TAP**
Carry-on size : 550 x 400 x 200
Carry-on weight : 8

Personal item size : 400 x 300 x 150
Personal item weight : 2

Source : `https://www.flytap.com/fr-fr/bagages/bagages-a-main`

**Comment by JenniferMack** [comment]
Will be in next push, I'll switch the links to english for consistency.
