### ISSUE TITLE
add GORUCK bags

### ISSUE THREAD

**Issue by x3n0n** [JenniferMack/BagsVsAirlines#9]
Thanks for doing this--I really enjoy using this!

reference: GORUCK.com

GR1 26L: 20 x 12 x 6.75 in (50.8 x 30.5 x 17.1 cm), 3.2 lb (1.45 kg)
GR1 21L: 18 x 11.5 x 5.5 in (45.7 x 29.2 x 13.9 cm), 2.9 lb (1.32 kg)
GR1 Women's (21L): 18 x 11.5 x 5.5 in (45.7 x 29.2 x 13.9 cm), 2.5 lb (1.13 kg)

GR2 40L: 22 x 12.5 x 9 in (55.9 x 31.8 x 22.9 cm), 4.75 lb (2.15 kg)
GR2 34L: 20.5 x 12.5 x 9 in (52.1 x 31.8 x 22.9 cm), 4.75 lb (2.15 kg)

GR3 (45L): 22 x 14 x 9 in (55.9 x 35.6 x 22.9 cm), 4.59 lb (2.09 kg) without hip belt (5.15/2.34 with)

Rucker 20L: 18 x 11.5 x 5.5 in (45.7 x 29.2 x 13.9 cm), 2.87 lb (1.30 kg)
Rucker 25L: 20 x 12 x 6.75 in (50.8 x 30.5 x 17.1 cm), 3.15? lb (1.43? kg) -- webpage unavailable right now for weight

Bullet 10L: 18.5 x 8.5 x 5 in (47 x 21.6 x 12.7 cm), 1.32 lb (0.6 kg)
Bullet 15L: 18.5 x 10 x 5.6 in (47 x 25.4 x 13.9cm), 1.55lb (0.7 kg)

**Comment by JenniferMack** [comment]
I really hate it when they don't give metric dimensions. I'll get this added for the next update.

**Comment by JenniferMack** [comment]
Will be in next push.
